name-template: 'v$RESOLVED_VERSION 📔'
tag-template: 'v$RESOLVED_VERSION'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
categories:
  - title: '🚀 Features'
    labels: 
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '📦 Dependencies'
    collapse-after: 3
    labels:
      - 'dependencies'
  - title: '🧰 Maintenance'
    label: 'chore'
  - title: '✅ Tests'
    labels:
      - 'test'
      - 'tests'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'
exclude-labels:
  - 'skip-changelog'
template: |
  ## Changes

  $CHANGES

  $CONTRIBUTORS